default_language_version:
  python: python3.12

files: |  # python regex
  (?x)      # verbose regex
  ^(?:      # start of filename
    lib/.*  # all working python
    |
    [^/]+   # top level files
  )$        # end of filename


repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.15
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix

  - repo: https://github.com/crate-ci/typos
    rev: v1.16.21
    hooks:
      - id: typos

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies: [ tomli ]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
        args: [ --number ]

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
      - id: auto-walrus
        args: [ --line-length=89 ]

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        name: ruff-show-errors
        args: [ --diff, --exit-non-zero-on-fix ]

      - id: ruff
        name: ruff-auto-fix
        args: [ --fix, --exit-non-zero-on-fix, --show-fixes ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.333
    hooks:
    - id: pyright

#  - repo: local
#    hooks:
#      - id: mypy-local
#        name: Mypy local
#        description: Run mypy with local sources.
#        entry: mypy
#        language: python
#        types: [ python ]
#        additional_dependencies:
#          - mypy==1.6.1
#          - qtpy
#          - PyQt5
#          - more-itertools
#          - ordered-set
#        args: [ --config=pyproject.toml ]
#        args: [--strict]
